### ISSUE TITLE
bug: command failed command sh -c create-stencil

### ISSUE THREAD

**Issue by pcreynolds** [ionic-team/create-stencil#217]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/create-stencil/issues) that already report this problem, without success.

### Create Stencil Version

@latest

### Current Behavior

When I run npm init stencil or npm init stencil@latest the Perparing starter process fails with

Protocol "https:" not supported. Expected "http:"

command failed
command sh -c create-stencil

### Expected Behavior

The stencil project should be initialized

### Steps to Reproduce

run npm init stencil or npm init stencil@latest

### Additional Information

I have http-proxy and https-proxy setup for my company proxy and I have tried with the registry config set to with both the http and https.

Works fine from my personal computer.

**Comment by rwaskiewicz** [comment]
Hey @pcreynolds 👋 

Thanks for the issue! To try to root cause this, can you provide us with some additional information please?

1. What is the output of running `npm --version` and `node --version` in a terminal window?
2. Can you let us know what Operating System/version you're using?
3. Can you provide additional details about http-proxy and https-proxy? I'm unsure if these are NPM packages or a corporate piece of software provided by some vendor. 

My hunch is that this is related to http-proxy/https-proxy, any info you can provide on this setup will be super helpful in root causing.

Thanks!

**Comment by pcreynolds** [comment]
I'm on a Apple M1 Pro
macOS Ventura Version 13.3.1

npm --verison
9.5.0

node --verison
v18.15.0

I have the http-proxy and https-proxy setup as needed. Works for other npm packages anyhow.

**Comment by rwaskiewicz** [comment]
Are those https://www.npmjs.com/package/http-proxy and https://www.npmjs.com/package/https-proxy? Something else? Can you provide more detail of what that setup looks like?

**Comment by pcreynolds** [comment]
Those values are something else. The pattern for both is http://{domain}:{port}.

The only thing I can think of is that my company proxy value is possibly causing an issue because of the required protocol.

**Comment by pcreynolds** [comment]
Looks like this is due to a security policy outside of my control.
