### ISSUE TITLE
Remove system specific files from .gitignore

### ISSUE THREAD

**Issue by Siilwyn** [ionic-team/create-stencil#22]
A smaller focused `.gitignore` containing only project (Stencil) related files would be great. Including user specific (system & editor) files should be done in a [global gitignore](https://davidwalsh.name/global-gitignore).

**Comment by rwaskiewicz** [comment]
👋 

I apologize for the amount of time it took to get to this issue! 

Looking at the contents of `.gitignore` around the [time this issue was created](https://github.com/ionic-team/create-stencil/blob/7da13265b3b5e951acbf59eecb69b4e245645255/.gitignore) as well as [today](https://github.com/ionic-team/create-stencil/blob/c517b831a8b76bfaf1ecb3c5eb8cc4820c97dc6b/.gitignore#L1-L5) I feel like the contents are appropriate.  The alternative is that folks don't have a global gitignore configured, and as a part of a PR accidentally commit one of the files we don't wish to persist in the repo. 

It's always a balancing act trying to find the correct level of items to add in a local vs global `.gitignore`, and that's not to say I/the Stencil team will always get things right 100% of the time. For now, I'm going to close this issue, but want to thank you for your input/thoughts!

Thanks again!
