### ISSUE TITLE
Wrong colors in Firefox in a freshly generated ionic-pwa app

### ISSUE THREAD

**Issue by adrm** [ionic-team/create-stencil#24]
Colors seems to be wrong when running an app generated with `npm init stencil`, and choosing `ionic-pwa` as the type. Starting the dev server with `npm start` and opening it on both Chrome and Firefox gives you this differences in colors.

![imagen](https://user-images.githubusercontent.com/307945/61221056-efc0ff00-a717-11e9-9ca2-2799b56f7132.png)

(I don't really know if this is an issue with this repo, with stencil or with Ionic. I haven't found a related issue in any of those projects' issue trackers.)

**Comment by Nudelsieb** [comment]
Colours are nort working at all in FF when selecting the `app` boilerplate. The header colours and other colours do briefly flash and then disappear when using the default settings. Switching off shadow DOM fixes the issue. I am not sure what is the issue but shadow DOM is supported in FF.

**Comment by rwaskiewicz** [comment]
Hey @adrm, 

I apologize that it took so long for a member of the team to acknowledge this issue. Due to the fact that the Stencil team is no longer supporting the PWA starter, I'm going to close this ticket. 

If you're still having an issue with the latest version of Ionic please feel free to open a new ticket [in the PWA starter repo](https://github.com/ionic-team/ionic-pwa-toolkit) (and if you're an Ionic Enterprise customer, please open a ZenDesk ticket).

I apologize once again for the delay!
