### ISSUE TITLE
ionic4 theming not working

### ISSUE THREAD

**Issue by joeSaad** [ionic-team/create-stencil#27]
- created an app using `npm init stencil`
- chose PWA
- added root css variables from the [theme generator](https://ionicframework.com/docs/theming/color-generator)
- configured _stencil.config.ts_ outputTargets to include *dist* as well 
- added **namespace** to _stencil.config.ts_
- ran `npm run build` and followed the needed files 
- followed instructions to add needed params to _package.json_ like **main**, **module**, **types** etc..
- imported this components library in my vuejs app
- running my vuejs app, it doesn't see my CSS root variables, even though it sees the components as needed but not the colors, so if i tried ```<ion-button color="primary">Primary</ion-button>```
it comes as a white button instead of the actual primary color which is blue as initially created in the stencil repo. 
Please advise. 
Thanks

**Comment by rwaskiewicz** [comment]
Hey @joeSaad 

I apologize that it took so long for a member of the team to acknowledge this issue.  Due to the fact that the Stencil team is no longer supporting the PWA starter and that [Ionic 4 is in extended support mode](https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status), I'm going to close this ticket.  If you're still having an issue with the latest version of Ionic please feel free to open a new ticket (and if you're an Ionic Enterprise customer, please open a ZenDesk ticket).

I apologize once again for the delay!
